# Stateless application specification -
# The Deployment creates a single replicated Pod, indicated by the 'replicas' field
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-quickstart-instance
    migrate-for-anthos-type: workload
  name: app-quickstart-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-quickstart-instance
      migrate-for-anthos-type: workload
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-quickstart-instance
        migrate-for-anthos-type: workload
    spec:
      containers:
      - image: gcr.io/kuchima03/quickstart-instance:v1.0.0
        name: app-quickstart-instance
        readinessProbe:
          exec:
            command:
            - /code/ready.sh
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys/fs/cgroup
          name: cgroups
      volumes:
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroups
status: {}

---
# Headless Service specification -
# No load-balancing, and a single cluster internal IP, only reachable from within the cluster
# The Kubernetes endpoints controller will modify the DNS configuration to return records (addresses) that point to the Pods, which are labeled with "app": "app-quickstart-instance"
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: app-quickstart-instance
spec:
  clusterIP: None
  selector:
    app: app-quickstart-instance
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: app-quickstart-instance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

